name: simplex-chat
version: 0.3.0
#synopsis:
#description:
homepage: https://github.com/simplex-chat/simplex-chat#readme
license: AGPL-3
author: Evgeny Poberezkin
maintainer: evgeny@poberezkin.com
copyright: 2020 Evgeny Poberezkin
category: Web, System, Services, Cryptography
extra-source-files:
  - README.md

executables:
  dog-food:
    source-dirs: apps/dog-food
    main: Main.hs
    dependencies:
      - base == 4.13.*
      - ansi-terminal == 0.10.*
      - async == 2.2.*
      - attoparsec == 0.13.*
      - bytestring == 0.10.*
      - directory == 1.3.*
      - filepath == 1.4.*
      - mtl == 2.2.*
      - optparse-applicative == 0.15.*
      - simple-logger == 0.1.*
      - simplexmq == 0.3.*
      - stm == 2.5.*
      - terminal == 0.2.*
      - text == 1.2.*
      - time == 1.9.*
      - unliftio == 0.2.*
    ghc-options:
      - -threaded

ghc-options:
  # - -haddock
  - -Wall
  - -Wcompat
  - -Werror=incomplete-patterns
  - -Wredundant-constraints
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wunused-type-patterns
