name: simplex-definitions
version: 0.1.0.0
#synopsis:
#description:
homepage: https://github.com/simplex-chat/protocol/blob/master/definitions/readme.md
license: AGPL-3
author: Evgeny Poberezkin
copyright: 2020 Evgeny Poberezkin
category: Web
extra-source-files:
  - readme.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Werror=incomplete-patterns
  - -Wredundant-constraints
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns

# default-extensions:
#   - BlockArguments
#   - DuplicateRecordFields
#   - LambdaCase
#   - NamedFieldPuns
#   - NoImplicitPrelude
#   - OverloadedStrings
#   - RecordWildCards

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - classy-prelude
  - decidable
  - lens
  - mtl
  - singletons
  - servant-docs
  - servant-server
  - template-haskell

library:
  source-dirs: src

executables:
  api-docs:
    source-dirs: app/api-docs
    main: Main.hs
    ghc-options: -threaded
    dependencies: simplex-definitions

  print-scenarios:
    source-dirs: app/print-scenarios
    main: Main.hs
    ghc-options: -threaded
    dependencies: simplex-definitions

tests:
  simplex-definitions-doctests:
    source-dirs: tests
    main: doctest-driver.hs
    ghc-options: -threaded
    dependencies:
      - doctest
      - doctest-driver-gen
