name: simplex-definitions
version: 0.1.0.0
#synopsis:
#description:
homepage: https://github.com/simplex-chat/protocol/blob/master/definitions/readme.md
license: AGPL-3
author: Evgeny Poberezkin
copyright: 2020 Evgeny Poberezkin
category: Web
extra-source-files:
  - readme.md

ghc-options:
  # - -fplugin=Polysemy.Plugin
  - -O2
  - -Wall
  - -Wcompat
  - -Werror=incomplete-patterns
  - -Wredundant-constraints
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wunused-type-patterns

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - freer-indexed
  - polysemy
  # - polysemy-plugin
  - lens
  - mtl
  - protocol
  - singletons
  - servant-docs
  - servant-server
  - text
  - transformers

library:
  source-dirs: src

executables:
  api-docs:
    source-dirs: app/api-docs
    main: Main.hs
    ghc-options: -threaded
    dependencies: simplex-definitions

  print-scenarios:
    source-dirs: app/print-scenarios
    main: Main.hs
    ghc-options: -threaded
    dependencies: simplex-definitions

tests:
  simplex-definitions-doctests:
    source-dirs: tests
    main: doctest-driver.hs
    ghc-options: -threaded
    dependencies:
      - doctest
      - doctest-driver-gen
