name:                simplex-definitions
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/simplex-chat/protocol/blob/master/definitions/readme.md
license:             AGPL-3
author:              Evgeny Poberezkin
copyright:           2020 Evgeny Poberezkin
category:            Web
extra-source-files:
- readme.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Werror=incomplete-patterns
  - -Wredundant-constraints
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns

default-extensions:
  - BlockArguments
  - DuplicateRecordFields
  - LambdaCase
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards
  
dependencies:
  - aeson
  - base >= 4.7 && < 5
  - classy-prelude
  - decidable
  - lens
  - singletons
  - servant-docs
  - servant-server
  - template-haskell
  # - pretty-show

library:
  source-dirs: src
  exposed-modules:
    - Predicate
    - Simplex.Messaging.Types
    - Simplex.Messaging.ServerAPI

executables:
  api-docs:
    source-dirs:      src
    main:             Main.hs

tests:
  simplex-definitions-doctests:
    source-dirs: tests
    main: doctest-driver.hs
    ghc-options: -threaded
    dependencies:
      - doctest
      - doctest-driver-gen
