name: Chat Lib Tests

on: [push]

jobs:
  test:

    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: cd packages/chat; 
          cmake . -Bbuild; 
          cd build;  
          cmake --build .; 
          ctest --verbose